Repository TIP-ZIP/TIPZIP_BE, pull requests merged in 2024-12, with the labels that each got.

#18 Feature/7 fix login
  src/main/java/mutsa/TIPZIP_BE/controller/AuthController.java
  src/main/java/mutsa/TIPZIP_BE/entity/RefreshToken.java
  src/main/java/mutsa/TIPZIP_BE/repository/RefreshTokenRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/MemberService.java
  src/main/java/mutsa/TIPZIP_BE/service/RefreshTokenService.java
Labels: enhancement

#20 Feature/get user
  build.gradle
  src/main/java/mutsa/TIPZIP_BE/controller/MemberTestController.java
  src/main/java/mutsa/TIPZIP_BE/dto/MemberDTO.java
  src/main/java/mutsa/TIPZIP_BE/service/MemberService.java
Labels: enhancement

#22 Feature/21 add mypage settings
  src/main/java/mutsa/TIPZIP_BE/config/SecurityConfig.java
  src/main/java/mutsa/TIPZIP_BE/controller/MyPageController.java
  src/main/java/mutsa/TIPZIP_BE/dto/MyPageResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/service/MemberService.java
Labels: enhancement

#23 Feature/17 add posts api
  .idea/compiler.xml
  src/main/java/mutsa/TIPZIP_BE/TipzipBeApplication.java
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/MyPostDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostRequestsDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostSimpleDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostRequestsDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/entity/Category.java
  src/main/java/mutsa/TIPZIP_BE/entity/Folder.java
  src/main/java/mutsa/TIPZIP_BE/entity/MemberEntity.java
  src/main/java/mutsa/TIPZIP_BE/entity/Post.java
  src/main/java/mutsa/TIPZIP_BE/entity/Scrap.java
  src/main/java/mutsa/TIPZIP_BE/entity/ScrapId.java
  src/main/java/mutsa/TIPZIP_BE/entity/Tag.java
  src/main/java/mutsa/TIPZIP_BE/repository/MemberRepository.java
  src/main/java/mutsa/TIPZIP_BE/repository/PostRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: enhancement

#26 Feature/17 add posts api
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/repository/PostRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: enhancement

#35 Bugfix/28 fix lazy initialization
  src/main/java/mutsa/TIPZIP_BE/controller/AuthController.java
  src/main/java/mutsa/TIPZIP_BE/controller/FollowController.java
  src/main/java/mutsa/TIPZIP_BE/service/MyPageService.java
Labels: bug

#36 Feature/31 add folder api
  src/main/java/mutsa/TIPZIP_BE/controller/FolderController.java
  src/main/java/mutsa/TIPZIP_BE/dto/FolderDTO/FolderCountResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/FolderDTO/FolderRequestsDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/FolderDTO/FolderResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/repository/FolderRepository.java
  src/main/java/mutsa/TIPZIP_BE/repository/ScrapRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/FolderService.java
Labels: enhancement

#40 Fix/39 token reissue and logout
  src/main/java/mutsa/TIPZIP_BE/config/SecurityConfig.java
  src/main/java/mutsa/TIPZIP_BE/controller/AuthController.java
  src/main/java/mutsa/TIPZIP_BE/dto/TokenResponseDTO/GoogleTokenResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/TokenResponseDTO/KakaoTokenResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/jwt/JwtTokenProvider.java
  src/main/java/mutsa/TIPZIP_BE/repository/RefreshTokenRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/AuthService/GoogleAuthService.java
  src/main/java/mutsa/TIPZIP_BE/service/AuthService/KakaoAuthService.java
  src/main/java/mutsa/TIPZIP_BE/service/AuthService/RefreshTokenService.java
  src/main/java/mutsa/TIPZIP_BE/service/MemberService.java
  src/main/java/mutsa/TIPZIP_BE/service/MyPageService.java
Labels: bug, enhancement

#42 Feature/38 add scrap api
  src/main/java/mutsa/TIPZIP_BE/controller/ScrapController.java
  src/main/java/mutsa/TIPZIP_BE/dto/FolderDTO/FolderCountResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/FolderDTO/FolderResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/ScrapDTO/ScrapRequestsDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/ScrapDTO/ScrapResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/entity/Folder.java
  src/main/java/mutsa/TIPZIP_BE/repository/FolderRepository.java
  src/main/java/mutsa/TIPZIP_BE/repository/ScrapRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/FolderService.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
Labels: enhancement

#45 Feat/41 add search
  src/main/java/mutsa/TIPZIP_BE/config/SecurityConfig.java
  src/main/java/mutsa/TIPZIP_BE/controller/SearchController.java
  src/main/java/mutsa/TIPZIP_BE/repository/PostRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/SearchService.java
Labels: enhancement

#47 Feature/43 add tag + fix scrap error
  src/main/java/mutsa/TIPZIP_BE/controller/TagController.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/MyPostDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostSimpleDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/ScrapDTO/ScrapResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/entity/Post.java
  src/main/java/mutsa/TIPZIP_BE/entity/Scrap.java
  src/main/java/mutsa/TIPZIP_BE/repository/ScrapRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
  src/main/java/mutsa/TIPZIP_BE/service/TagService.java
  src/main/resources/db/data.sql
Labels: bug, enhancement

#50 Feature/37 add post update
  src/main/java/mutsa/TIPZIP_BE/controller/FolderController.java
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/entity/Post.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
Labels: bug, enhancement

#53 Feature/51 add get following posts
  src/main/java/mutsa/TIPZIP_BE/S3Storage/S3Controller.java
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/repository/FollowRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: enhancement

#54 Refactor/44 mypage and search
  src/main/java/mutsa/TIPZIP_BE/controller/SearchController.java
  src/main/java/mutsa/TIPZIP_BE/dto/MyPageResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/repository/PostRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/MyPageService.java
  src/main/java/mutsa/TIPZIP_BE/service/SearchService.java
Labels: bug, enhancement

#57 Fix/56 cert follow getpost test
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/dto/MemberDTO.java
  src/main/java/mutsa/TIPZIP_BE/entity/MemberEntity.java
  src/main/java/mutsa/TIPZIP_BE/repository/FollowRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: bug

#59 Feature/58 add add cert member
  src/main/java/mutsa/TIPZIP_BE/controller/AuthController.java
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/dto/MemberResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/entity/ScrapId.java
  src/main/java/mutsa/TIPZIP_BE/repository/ScrapRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/MemberService.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: bug, enhancement

#61 fix(Post-follow): fit getFollowPosts functionality (#60)
  src/main/java/mutsa/TIPZIP_BE/repository/PostRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: bug

#63 fix(service):state설정 추가(#62)
  src/main/java/mutsa/TIPZIP_BE/service/AuthService/NaverAuthService.java
Labels: bug

#65 Feature/64 add sort search
  src/main/java/mutsa/TIPZIP_BE/controller/SearchController.java
  src/main/java/mutsa/TIPZIP_BE/service/SearchService.java
Labels: enhancement

#67 Fix/66 fix get posts
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/repository/PostRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: bug, enhancement

#69 Fix/68 fix exception handle
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: bug

#74 fix(service):기존 회원이 로그인시 기존 유저네임,뱃지 정보 매핑(#73)
  src/main/java/mutsa/TIPZIP_BE/service/MemberService.java
Labels: bug

#76 fix(Post): fix ResponseDTO to contain user_id, category, profile_imag…
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostSimpleDTO.java
Labels: bug

#80 feat(Post): add getMyPosts (#78)
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
Labels: enhancement

#84 Fix/83 post content length
  src/main/java/mutsa/TIPZIP_BE/entity/Post.java
Labels: bug

#88 feat(Scrap) : get scrap by folderName (#87)
  src/main/java/mutsa/TIPZIP_BE/controller/ScrapController.java
Labels: bug, enhancement

#91 Fix/89 fix scrap category
  src/main/java/mutsa/TIPZIP_BE/controller/FolderController.java
  src/main/java/mutsa/TIPZIP_BE/repository/FolderRepository.java
  src/main/java/mutsa/TIPZIP_BE/repository/ScrapRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/FolderService.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
Labels: bug

#95 fix(Scrap): scrap with folder_name (#93)
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
Labels: bug

#96 fix(Folder): fix getFolderList (#93)
  src/main/java/mutsa/TIPZIP_BE/dto/FolderDTO/FolderCountResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/service/FolderService.java
Labels: bug

#97 fix(Post): isScrapped (#93)
  src/main/java/mutsa/TIPZIP_BE/controller/PostController.java
  src/main/java/mutsa/TIPZIP_BE/controller/SearchController.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/MyPostDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostSimpleDTO.java
  src/main/java/mutsa/TIPZIP_BE/entity/Post.java
  src/main/java/mutsa/TIPZIP_BE/repository/ScrapRepository.java
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
  src/main/java/mutsa/TIPZIP_BE/service/SearchService.java
Labels: bug

#99 feat(Post): add category for MyPostDTO (#98)
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/MyPostDTO.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
Labels: enhancement

#101 fix(Get) (#100)
  src/main/java/mutsa/TIPZIP_BE/service/PostService.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
Labels: bug

#103 fix(Post): delete (#102)
  src/main/java/mutsa/TIPZIP_BE/entity/Post.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
Labels: bug

#105 Fix/104 permitall search
  src/main/java/mutsa/TIPZIP_BE/controller/SearchController.java
  src/main/java/mutsa/TIPZIP_BE/dto/PostDTO/PostSearchResponseDTO.java
  src/main/java/mutsa/TIPZIP_BE/service/SearchService.java
Labels: bug

#108 fix(Scrap): change getFolder Get to Post (#102)
  src/main/java/mutsa/TIPZIP_BE/controller/ScrapController.java
  src/main/java/mutsa/TIPZIP_BE/entity/Folder.java
  src/main/java/mutsa/TIPZIP_BE/entity/MemberEntity.java
  src/main/java/mutsa/TIPZIP_BE/service/ScrapService.java
Labels: bug

#111 fix(Post): longer
  src/main/java/mutsa/TIPZIP_BE/entity/Post.java
Labels: bug
